version: '2'
services:
  django:
    image: gohitech/django:djcelery
    build: .
    environment:
      - DJANGO_ADMINS=[('John', 'john@example.com'), ('Mary', 'mary@example.com')]
      - DJANGO_DEBUG=False
      - GUNICORN_WORKER_CLASS=gevent
      - POSTGRES_PASSWORD=password
    links:
      - db
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./share:/share
  celery:
    image: gohitech/django:djcelery
    command: --loglevel=INFO --autoreload
    environment:
      - CELERY_ENABLE=True
      - POSTGRES_PASSWORD=password
    links:
      - db
  beat:
    image: gohitech/django:djcelery
    command: --loglevel=INFO
    environment:
      - CELERY_ENABLE=beat
      - POSTGRES_PASSWORD=password
    links:
      - db
  other:
    image: gohitech/django:djcelery
    command: ["tail","-f","/dev/null",]
    environment:
      - GUNICORN_ENABLE=False
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
  rabbitmq:
    image: rabbitmq:3
