version: '2'
services:
  django:
    build: .
    environment:
      - DJANGO_ADMINS=[('John', 'john@example.com'), ('Mary', 'mary@example.com')]
      - DJANGO_DEBUG=True
      - GUNICORN_WORKER_CLASS=gevent
      - POSTGRES_PASSWORD=password
    links:
      - db
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./share:/share
  celery:
    image: dockerdjango_django
    command: --loglevel=INFO
    environment:
      - CELERY_ENABLE=True
  other:
    image: dockerdjango_django
    command: ["tail","-f","/dev/null",]
    environment:
      - GUNICORN_ENABLE=False
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
  rabbitmq:
    image: rabbitmq:3
